language: csharp
mono: latest
dotnet: 2.1.300
install:
  - msbuild -t:Restore -p:Configuration=Release
  - nuget install NUnit.ConsoleRunner -Version 3.8.0 -OutputDirectory testrunner
script:
  - msbuild MonoDevelop.Xml.sln -p:Configuration=Release
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./Tests/bin/Release/MonoDevelop.Xml.Tests.dll